apiVersion: apps/v1
kind: Deployment
metadata:
  name: alejandro-duarte
spec:
  replicas: 1
  selector:
   matchLabels:
     app: alejandro-duarte
  template:
   metadata:
     labels:
       app: alejandro-duarte
   spec:
     containers:
       - name: alejandro-duarte
         image: gcr.io/badboydevop/teamwebsite
         ports:
         - containerPort: 3000
         resources:
          limits:
            cpu: 100m
            memory: 250M
          requests:
            cpu: 50m
            memory: 100M
---
apiVersion: v1
kind: Service
metadata:
  name: alejandro-service
spec:
  selector:
    app: alejandro-duarte
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 3000
---