apiVersion: apps/v1
kind: Deployment
metadata:
  name: derek-washburn
spec:
  replicas: 1
  selector:
    matchLabels:
      app: derek-washburn
  template:
    metadata:
      labels:
        app: derek-washburn
    spec:
      containers:
      - name: derek-washburn
        image: image=gcr.io/badboydevop/teamwebsite
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 100m
            memory: 250M
          requests:
            cpu: 50m
            memory: 100M
