apiVersion: apps/v1
kind: Deployment
metadata:
  name: derek-washburn
spec:
  replicas: 1
  selector:
    matchLabels:
      app: derek-washburn
  template:
    metadata:
      labels:
        app: derek-washburn
    spec:
      containers:
      - name: derek-washburn
        image: gcr.io/badboydevop/teamwebsite
        ports:
        - containerPort: 3000
        resources:
          limits:
            cpu: 100m
            memory: 250M
          requests:
            cpu: 50m
            memory: 100M
---
apiVersion: v1
kind: Service
metadata:
  name: derekWashburn-service
spec:
  selector:
    app: derek-washburn
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 3000