apiVersion: apps/v1
kind: Deployment
metadata:
  name: dorian-lapi-team
spec: 
  replicas: 1
  selector:
    matchLabels:
      app: dorian-lapi-team
  template:
    metadata:
      labels:
        app: dorian-lapi-team
    spec:
      containers:
      - name: dorian-lapi-team
        image: nginx
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 100m
            memory: 250M
          requests:
            cpu: 50m
            memory: 100M



