apiVersion: apps/v1
kind: Deployment
metadata:
  name: dorian-lapi
spec: 
  replicas: 1
  selector:
    matchLabels:
      app: dorian-lapi
  template:
    metadata:
      labels:
        app: dorian-lapi
    spec:
      containers:
      - name: dorian-lapi
        image: gcr.io/badboydevop/teamwebsite
        ports:
        - containerPort: 3000
        resources:
          limits:
            cpu: 100m
            memory: 250M
          requests:
            cpu: 50m
            memory: 100M
---
apiVersion: v1
kind: Service
metadata: 
  name: dorian-service
spec:
  selector:
    app: dorian-lapi
  type: LoadBalancer
  ports: 
  - port: 80
    targetPort: 3000
---


